// API Endpoints configuration
export const API_ENDPOINTS = {
  auth: {
    login: '/accounts/login/',
    signup: '/accounts/signup/',
    verifyEmail: (token: string) => `/accounts/verify-email/${token}/`,
    resendVerification: '/accounts/resend-verification/',
    passwordReset: '/accounts/password-reset/',
    passwordResetConfirm: (token: string) => `/accounts/password-reset/${token}/`,
    logout: '/accounts/logout/',
    profile: '/accounts/profile/',
    changePassword: '/accounts/change-password/',
    googleLogin: '/accounts/google/login/',
  },
  marketplace: {
    vehicles: '/marketplace/vehicles/',
    vehicle: (id: string) => `/marketplace/vehicles/${id}/`,
    sellRequests: '/marketplace/sell-requests/',
    sellRequest: (id: string) => `/marketplace/sell-requests/${id}/`,
    bookings: '/marketplace/bookings/',
  },
  services: {
    categories: '/repairing-service/categories/',
    services: '/repairing-service/services/',
    servicePrice: (id: string) => `/repairing-service/services/${id}/price/`,
    createCart: '/repairing-service/cart/create/',
    listCarts: '/repairing-service/cart/',
    cartDetail: (id: number) => `/repairing-service/cart/${id}/`,
    addToCart: (cartId: number) => `/repairing-service/cart/${cartId}/add/`,
    updateCartItem: (cartId: number) => `/repairing-service/cart/${cartId}/update/`,
    clearCart: (cartId: number) => `/repairing-service/cart/${cartId}/clear/`,
    removeCartItem: (itemId: number) => `/repairing-service/cart/item/${itemId}/remove/`,
    myRepairs: '/repairing-service/my-repairs/',
    serviceNow: '/repairing-service/service-now/',
    createBooking: '/repairing-service/bookings/create/',
  },
  profile: {
    details: '/accounts/profile/',
    changePassword: '/accounts/change-password/',
  },
  subscription: {
    plans: '/subscription/plans/',
    planDetails: (id: string) => `/subscription/plans/${id}/`,
    planVariants: '/subscription/plan-variants/',
    getPlanVariants: (planId: string) => `/subscription/plans/${planId}/variants/`,
    requests: '/subscription/requests/',
    requestStatus: (id: string) => `/subscription/requests/${id}/status/`,
    approveRequest: (id: string) => `/subscription/requests/${id}/approve/`,
    rejectRequest: (id: string) => `/subscription/requests/${id}/reject/`,
    subscriptions: '/subscription/subscriptions/',
    activeSubscription: '/subscription/active/',
    cancelSubscription: (id: string) => `/subscription/subscriptions/${id}/cancel/`,
    visits: {
      upcoming: '/subscription/visits/upcoming/',
      cancel: (id: number) => `/subscription/visits/${id}/cancel/`,
    },
    checkVisitAvailability: '/subscription/visits/check-availability/',
    visitHistory: '/subscription/visits/history/',
    visitSummary: '/subscription/visits/summary/',
    completeVisit: (id: string) => `/subscription/visits/${id}/complete/`,
    subscriptionStatus: (id: string) => `/subscription/subscriptions/${id}/status/`,
  },
  vehicle: {
    types: '/vehicles/types/',
    manufacturers: '/vehicles/manufacturers/',
    models: '/vehicles/models/',
    userVehicles: '/vehicles/user-vehicles/',
    checkCloudinary: '/vehicles/check-cloudinary/',
    vehicleImages: (id: string) => `/vehicles/${id}/images/`,
    uploadParams: (id: string) => `/vehicles/${id}/upload-params/`,
  },
  spareParts: {
    list: '/spare-parts/',
    detail: (id: string) => `/spare-parts/${id}/`,
    categories: '/spare-parts/categories/',
    reviews: (partId: string) => `/spare-parts/${partId}/reviews/`,
    related: (partId: string) => `/spare-parts/${partId}/related/`,
    featured: '/spare-parts/featured/',
    byVehicle: '/spare-parts/by-vehicle/',
    search: '/spare-parts/search/',
    filter: '/spare-parts/filter/',
  },
  cdn: {
    baseUrl: 'https://res.cloudinary.com/repairmybike',
  },
}; 